### ISSUE TITLE
QA - Test All Numerically Ordered SQL Files

### ISSUE THREAD

**Issue by ianfrantz** [fdrennan/Zomato-SQL#3]
I'll test the file execution in a Docker Postgres container once you put them in named order @fdrennan. :]

Keep up the great work.
-Ian

**Comment by fdrennan** [comment]
Ok, I'll do that and update master this morning.

**Comment by fdrennan** [comment]
Put the correct order of the files in master. The problem seems to be after the CSV copy. It takes a minute for the data to actually get into the DB and creating the tables in the script might be going faster than the DB can keep up. Maybe a sys.sleep or is there a smarter way? Possibly checking if the table exists and then running the rest of the view files.

**Comment by ianfrantz** [comment]
All files tested successfully. :] I have the build running. Let me know if you want me to test changes.

**Comment by fdrennan** [comment]
Open a PR! I'd love to check it out.
